const countryNames: { [key: string]: string } = {
  AF: "Afghanistan",
  AX: "Åland Islands",
  AL: "Albania Albanië Shqipëria",
  DZ: "Algeria Algerije Dzayer",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina Argentinië",
  AM: "Armenia Armenië Hayastan",
  AW: "Aruba",
  AU: "Australia Australië",
  AT: "Austria Oostenrijk Österreich",
  AZ: "Azerbaijan Azerbeidzjan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus Wit-Rusland",
  BE: "Belgium België Belgique",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BQ: "Bonaire Sint Eustatius Saba",
  BA: "Bosnia and Herzegovina Bosnië",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil Brazilië Brasil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria Bulgarije",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia Cambodja",
  CM: "Cameroon Kameroen",
  CA: "Canada",
  CV: "Cape Verde Kaapverdië",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad Tsjaad",
  CL: "Chile Chili",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo Democratic Republic",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire Ivoorkust",
  HR: "Croatia Kroatië Hrvatska",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czech Republic Tsjechië Česko",
  DK: "Denmark Denemarken Danmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic Dominicaanse Republiek",
  EC: "Ecuador",
  EG: "Egypt Egypte",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia Estland Eesti",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands Faeröer",
  FJ: "Fiji",
  FI: "Finland Suomi",
  FR: "France Frankrijk",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia Georgië Sakartvelo",
  DE: "Germany Duitsland Deutschland",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece Griekenland Hellas",
  GL: "Greenland Groenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti Haïti",
  HM: "Heard Island",
  VA: "Vatican City Vaticaanstad",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary Hongarije Magyarország",
  IS: "Iceland IJsland Ísland",
  IN: "India",
  ID: "Indonesia Indonesië",
  IR: "Iran",
  IQ: "Iraq Irak",
  IE: "Ireland Ierland Éire",
  IM: "Isle of Man",
  IL: "Israel Israël",
  IT: "Italy Italië Italia",
  JM: "Jamaica",
  JP: "Japan Nihon",
  JE: "Jersey",
  JO: "Jordan Jordanië",
  KZ: "Kazakhstan Kazachstan",
  KE: "Kenya Kenia",
  KI: "Kiribati",
  KP: "North Korea Noord-Korea",
  KR: "South Korea Zuid-Korea",
  KW: "Kuwait Koeweit",
  KG: "Kyrgyzstan Kirgizië",
  LA: "Laos",
  LV: "Latvia Letland Latvija",
  LB: "Lebanon Libanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya Libië",
  LI: "Liechtenstein",
  LT: "Lithuania Litouwen Lietuva",
  LU: "Luxembourg Luxemburg",
  MO: "Macao",
  MK: "North Macedonia Macedonië",
  MG: "Madagascar Madagaskar",
  MW: "Malawi",
  MY: "Malaysia Maleisië",
  MV: "Maldives Malediven",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania Mauritanië",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico México",
  FM: "Micronesia",
  MD: "Moldova Moldavië",
  MC: "Monaco",
  MN: "Mongolia Mongolië",
  ME: "Montenegro Crna Gora",
  MS: "Montserrat",
  MA: "Morocco Marokko Maghrib",
  MZ: "Mozambique",
  MM: "Myanmar Birma",
  NA: "Namibia Namibië",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands Nederland Holland",
  NC: "New Caledonia",
  NZ: "New Zealand Nieuw-Zeeland",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway Noorwegen Norge",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine Palestina",
  PA: "Panama Panamá",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru Perú",
  PH: "Philippines Filipijnen",
  PN: "Pitcairn",
  PL: "Poland Polen Polska",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Réunion, Reunion",
  RO: "Romania Roemenië România",
  RU: "Russia Rusland Rossiya",
  RW: "Rwanda",
  BL: "Saint Barthélemy",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome",
  SA: "Saudi Arabia Saudi-Arabië",
  SN: "Senegal",
  RS: "Serbia Servië Srbija",
  SC: "Seychelles Seychellen",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten",
  SK: "Slovakia Slowakije Slovensko",
  SI: "Slovenia Slovenië Slovenija",
  SB: "Solomon Islands",
  SO: "Somalia Somalië",
  ZA: "South Africa Zuid-Afrika",
  GS: "South Georgia",
  SS: "South Sudan",
  ES: "Spain Spanje España",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard Jan Mayen",
  SZ: "Eswatini Swaziland",
  SE: "Sweden Zweden Sverige",
  CH: "Switzerland Zwitserland Schweiz Suisse",
  SY: "Syria Syrië",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia Tunesië",
  TR: "Turkey Turkije Türkiye",
  TM: "Turkmenistan",
  TC: "Turks and Caicos",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine Oekraïne Ukrayina",
  AE: "United Arab Emirates VAE",
  GB: "United Kingdom UK Engeland England Britain",
  US: "United States USA Amerika America",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan Oezbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam Viêt Nam",
  VG: "Virgin Islands British",
  VI: "Virgin Islands U.S.",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe"
};
